spec:
  template:
    spec:
      serviceAccountName: "consultarembargos"
      volumes:
        - name: "consultarembargos"
          secret:
            # The secret must be created before deploying this application
            secretName: "consultarembargos"
      containers:
        -
          volumeMounts:
            - name: "consultarembargos"
              readOnly: true
              # Mount the secret where spring-cloud-kubernetes is configured to read it
              # see src/main/resources/bootstrap.yml
              mountPath: "/deployments/data/"
          resources:
           requests:
             cpu: "0.2"
             memory: 256Mi
           limits:
             cpu: "1.0"
             memory: 256Mi
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
